- README.md
However, some of the info is clearly out of date and it will need more.
Signed-off-by: "jwoehr@softwoehr.com"
> Made a README.md from readme.html

- src/main/java/com/ibm/as400/access/AS400ImplRemote.java
- src/main/java/com/ibm/as400/access/SignonConverter.java
> bugfix: handle `!` in password for DDM server

- src/main/java/com/ibm/as400/access/AS400JDBCDriver.java
Fixing bug introduced by recent changes and reported by https://sourceforge.net/p/jt400/bugs/475/
> JDBC: Fix for sourceforge bug #475

- src/main/java/com/ibm/as400/access/Copyright.java
Manually updated date to be shown by AboutToolbox
> Manually update build date

- .github/workflows/release.yml
> CI: Change to maintained action in Release workflow

- pom-dist.xml
> Exclude native classes during packaging phase

- src/main/resources/com/ibm/as400/data/pcml.dtd
> Add PCML version 8 to `pcml.dtd`

- src/main/java/com/ibm/as400/access/IFSFile.java
- src/main/java/com/ibm/as400/access/IFSFileEnumeration.java
> IFSFileEnumeration typesafety

- src/main/java/com/ibm/as400/access/Permission.java
List variants for permission APIs #77
> List variants for getAuthorizedUsers() and getUserPermissions()

- src/main/java/com/ibm/as400/access/AS400.java
- src/main/java/com/ibm/as400/access/AS400Impl.java
- src/main/java/com/ibm/as400/access/AS400ImplProxy.java
- src/main/java/com/ibm/as400/access/AS400ImplRemote.java
Signed-off-by: Liam Allan <mrliamallan@live.co.uk>
> Initial work to use GSSCredential interface

- pom.xml
> Fixup build for GitHub CodeSpaces

- src/main/java/com/ibm/as400/access/ProductList.java
A better solution to the product list bug. Introducing a new constant, used with the filter list option, that is the actual proper API value instead of converting *ALL to blanks.
> Enhancement Product List

- src/main/java/com/ibm/as400/access/PTF.java
The superseded by PTF is returned with the PTFR0100 format (which is the basic info format), and just needed to be captured from the output. The superseded PTF chain needed the implementation of the PTFR1000 format. A superseded PTF chain is all the PTFs that are superseded by this PTF. Also updated wording for getSupersedingPTF function to better articulate what it actually returns compared to getSupersededByPTF.
> Enhancement PTF

- src/main/java/com/ibm/as400/access/JobLog.java
> JobLog getMessages() typesafety

- pom-dist.xml
Same as #101 but for pom-dist.xml
> Provided scope for maven-antrun-plugin dependency

- pom-dist.xml
- src/main/javadoc/com/ibm/as400/access/doc-files/AFPResourceAttrs.html
- src/main/javadoc/com/ibm/as400/access/doc-files/JDBCProperties.html
- src/main/javadoc/com/ibm/as400/access/doc-files/LDRWExample.html
- src/main/javadoc/com/ibm/as400/access/doc-files/OutputQueueAttrs.html
- src/main/javadoc/com/ibm/as400/access/doc-files/PrintAttributes.html
- src/main/javadoc/com/ibm/as400/access/doc-files/PrinterAttrs.html
- src/main/javadoc/com/ibm/as400/access/doc-files/PrinterFileAttrs.html
- src/main/javadoc/com/ibm/as400/access/doc-files/RLReadFileExample.html
- src/main/javadoc/com/ibm/as400/access/doc-files/SQLTypes.html
- src/main/javadoc/com/ibm/as400/access/doc-files/SpooledFileAttrs.html
- src/main/javadoc/com/ibm/as400/access/doc-files/SystemProperties.html
- src/main/javadoc/com/ibm/as400/access/doc-files/SystemPropertiesSample1.html
- src/main/javadoc/com/ibm/as400/access/doc-files/SystemPropertiesSample2.html
- src/main/javadoc/com/ibm/as400/access/doc-files/TransInStr.html
- src/main/javadoc/com/ibm/as400/access/doc-files/WriterJobAttrs.html
- src/main/javadoc/com/ibm/as400/access/doc-files/codedisclaimer.htm
- src/main/javadoc/com/ibm/as400/access/doc-files/recordxmp.html
- src/main/javadoc/com/ibm/as400/micro/doc-files/JDBCProperties.html
- src/main/javadoc/com/ibm/as400/vaccess/doc-files/PrintAttributes.html
- src/main/javadoc/com/ibm/as400/vaccess/doc-files/SpooledFileAttrs.html
- src/main/javadoc/utilities/doc-files/ccsidList.html
- src/main/javadoc/utilities/doc-files/componentList.html
> doc-files fixes and modernization

- src/main/java/com/ibm/as400/access/AS400.java
- src/main/java/com/ibm/as400/access/AS400Impl.java
- src/main/java/com/ibm/as400/access/AS400ImplProxy.java
- src/main/java/com/ibm/as400/access/AS400ImplRemote.java
- src/main/java/com/ibm/as400/access/AS400NoThreadServer.java
- src/main/java/com/ibm/as400/access/AS400Server.java
- src/main/java/com/ibm/as400/access/AS400StrSvrDS.java
- src/main/java/com/ibm/as400/access/AS400ThreadedServer.java
- src/main/java/com/ibm/as400/access/AS400XChgRandSeedDS.java
- src/main/java/com/ibm/as400/access/AS400XChgRandSeedReplyDS.java
- src/main/java/com/ibm/as400/access/ClientAccessDataStream.java
- src/main/java/com/ibm/as400/access/HCSGetNewConnDS.java
- src/main/java/com/ibm/as400/access/HCSGetNewConnReplyDS.java
- src/main/java/com/ibm/as400/access/HCSPrepareNewConnDS.java
- src/main/java/com/ibm/as400/access/HCSPrepareNewConnReplyDS.java
- src/main/java/com/ibm/as400/access/HCSRequestedService.java
- src/main/java/com/ibm/as400/access/HCSRouteNewConnDS.java
- src/main/java/com/ibm/as400/access/HCSRouteNewConnReplyDS.java
- src/main/java/com/ibm/as400/access/PortMapper.java
Early additional authentication support for Toolbox that is intended to be used as a starting point for future development.
> Early Additional Authentication Support

- src/main/java/com/ibm/as400/access/EnhancedProfileTokenImplNative.java
Add framework for Native Enhanced Profile Tokens
> Native Enhanced Profile Token Framework

- src/main/java/com/ibm/as400/access/AS400.java
- src/main/java/com/ibm/as400/access/User.java
User class updated to include new MFA-related fields.  AS400 class method setStayAlive() updated to seconds from milliseconds and also optimized code so that it wakes at least every 30 seconds.
> User and AS400 class updates

- src/main/java/com/ibm/as400/security/auth/ProfileTokenImplRemote.java
> Enhanced profile tokens - index out of bounds error

- src/main/java/com/ibm/as400/access/AS400FileImplNative.java
- src/main/java/com/ibm/as400/access/AS400ImplProxy.java
- src/main/java/com/ibm/as400/access/AS400ImplRemote.java
- src/main/java/com/ibm/as400/access/BaseDataQueueImplNative.java
- src/main/java/com/ibm/as400/access/IFSFile.java
- src/main/java/com/ibm/as400/access/ProfileTokenImplNative.java
- src/main/java/com/ibm/as400/access/RemoteCommandImplNative.java
- src/main/java/com/ibm/as400/access/UserSpaceImplNative.java
- src/main/java/com/ibm/as400/access/jdbcClient/Main.java
- src/main/java/com/ibm/as400/security/auth/ProfileTokenCredential.java
- src/main/java/com/ibm/as400/security/auth/ProfileTokenImpl.java
- src/main/java/com/ibm/as400/security/auth/ProfileTokenImplRemote.java
- src/main/java/com/ibm/as400/security/auth/RefreshFailedException.java
- src/main/java/com/ibm/as400/security/auth/Swapper.java
IFSFile CCSID fix, jdbcClient reflection fix, swap refactoring, Profile token fixes.
> IFSFile CCSID fix, jdbcClient reflection fix, swap refactoring,

- src/main/java/com/ibm/as400/access/AS400.java
- src/main/java/com/ibm/as400/access/AS400ImplNative.java
- src/main/java/com/ibm/as400/access/AS400ImplRemote.java
Native optimization with regards to swapping has to be sensitive to MFA.
> Enhanced profile handle
